In [49]:
import numpy as np
import matrix_generator


# Matrix generation


In [50]:
N = 5
scale = 5

A = matrix_generator.generate_inv_mat(N, scale)         #   
A = matrix_generator.matJacobiCorr(A)                   #   corrects the matrix so that it fits Jacobi condition
x_ref, f = matrix_generator.matrixToSLE(A, scale)       #

[14. -5.  0. -4. -4.] [  3] -> [57.0]
[-2. 17.  2. -2. -2.] [ -3] -> [-51.0]
[ 4. -5. 17.  4.  1.] [  3] -> [78.0]
[-2. -8.  0.  8. -2.] [  0] -> [18.0]
[-2. -4.  5.  0. 10.] [  0] -> [21.0]


# Solving linear system

In [53]:
x = np.array([1]*N)

N_iterations = 10000

for cycle in range(N_iterations):
    x_old = x.copy()
    for j in range(N):  
        x[j] = f[j]/A[j][j] - np.dot(A[j]/A[j][j], x) + x_old[j]


# Comparing result with reference

In [54]:
print(x)
print(x_ref)

[ 3 -2  3  1  0]
[ 3 -3  3  0  0]
